[package]
name = "geopad-foundation"
version = "0.0.1"
authors = ["Liby Lee <liby99@icloud.com>"]
edition = "2018"

[lib]
name = "geopad_foundation"

[dependencies]
core-lib = { path = "../../core/lib" }
core-ui = { path = "../../core/ui" }
specs = "0.15"
piston_window = "0.120"