[package]
name = "geometry-sketchpad"
version = "0.1.0"
authors = ["Liby Lee <liby99@icloud.com>"]
edition = "2018"

[dependencies]
piston_window = "0.98"
specs = "0.15"
shrev = "1.1"
itertools = "0.8"