[package]
name = "core-piston"
version = "0.0.1"
authors = ["Liby Lee <liby99@icloud.com>"]
edition = "2018"

[dependencies]
core-lib = { path = "../lib" }
core-ui = { path = "../ui" }
specs = "0.15"
piston_window = "0.98"