[package]
name = "geopad-core-foundation"
version = "0.0.1"
authors = ["Liby Lee <liby99@icloud.com>"]
edition = "2018"

[dependencies]
geopad-core-lib = { path = "../lib" }
specs = "0.15"
shrev = "1.1"
piston_window = "0.98"